database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: ""
  name: "na"

auth:
  secret: "d0GKT6mfr5Nf/VSqBvNFfN5gaZ8KOiLdKaJ1aqQGLeQ="
  expire: '7d'
  bcrypt: "m8c0wJ84QPgG54AqWKvys9eIb9kvtXga01VzUrqUxHE="